spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sms_db
    username: sms_user
    password: P@s$w0rd2023
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    show-sql: true