INSERT INTO public.groups (name) VALUES ('ИТб-2301-01-00');
INSERT INTO public.groups (name) VALUES ('ИТб-2302-01-00');

INSERT INTO public.students (credit_card, first_name, last_name, middle_name, group_id) VALUES ('000001', 'Алина', 'Абрамовских', 'Александровна', 1);
INSERT INTO public.students (credit_card, first_name, last_name, middle_name, group_id) VALUES ('000001', 'Егор', 'Безденежных', 'Алексеевич', 1);
INSERT INTO public.students (credit_card, first_name, last_name, middle_name, group_id) VALUES ('000001', 'Александр', 'Бронников', 'Васильевич', 1);
INSERT INTO public.students (credit_card, first_name, last_name, middle_name, group_id) VALUES ('000001', 'Леонид', 'Бузмаков', 'Денисович', 1);
INSERT INTO public.students (credit_card, first_name, last_name, middle_name, group_id) VALUES ('000001', 'Павел', 'Бутолин', 'Иванович', 1);
INSERT INTO public.students (credit_card, first_name, last_name, middle_name, group_id) VALUES ('000001', 'Диана', 'Гаврилова', 'Васильевна', 1);
INSERT INTO public.students (credit_card, first_name, last_name, middle_name, group_id) VALUES ('000001', 'Дарья', 'Головизнина', 'Тимуровна', 1);
INSERT INTO public.students (credit_card, first_name, last_name, middle_name, group_id) VALUES ('000001', 'Ирина', 'Ерофеевская', 'Максимовна', 1);
INSERT INTO public.students (credit_card, first_name, last_name, middle_name, group_id) VALUES ('000001', 'Станислав', 'Каргапольцев', 'Владимирович', 1);
INSERT INTO public.students (credit_card, first_name, last_name, middle_name, group_id) VALUES ('000001', 'Данил', 'Кузнецов', 'Дмитриевич', 1);
INSERT INTO public.students (credit_card, first_name, last_name, middle_name, group_id) VALUES ('000001', 'Тимофей', 'Кулаков', 'Дмитриевич', 1);
INSERT INTO public.students (credit_card, first_name, last_name, middle_name, group_id) VALUES ('000001', 'Дмитрий', 'Лапшин', 'Витальевич', 1);
INSERT INTO public.students (credit_card, first_name, last_name, middle_name, group_id) VALUES ('000001', 'Никита', 'Мангутов', 'Рустамович', 1);
INSERT INTO public.students (credit_card, first_name, last_name, middle_name, group_id) VALUES ('000001', 'Святослав', 'Маракулин', 'Алексеевич', 1);
INSERT INTO public.students (credit_card, first_name, last_name, middle_name, group_id) VALUES ('000001', 'Даниил', 'Метелев', 'Андреевич', 1);
INSERT INTO public.students (credit_card, first_name, last_name, middle_name, group_id) VALUES ('000001', 'Махмуд', 'Мехрубони', ' ', 1);
INSERT INTO public.students (credit_card, first_name, last_name, middle_name, group_id) VALUES ('000001', 'Матвей', 'Миролюбов', 'Александрович', 1);
INSERT INTO public.students (credit_card, first_name, last_name, middle_name, group_id) VALUES ('000001', 'Артур', 'Мухатаев', 'Валерьевич', 1);
INSERT INTO public.students (credit_card, first_name, last_name, middle_name, group_id) VALUES ('000001', 'Умархон', 'Одинаев', 'Наимджонович', 1);
INSERT INTO public.students (credit_card, first_name, last_name, middle_name, group_id) VALUES ('000001', 'Вячеслав', 'Олюнин', 'Константинович', 1);
INSERT INTO public.students (credit_card, first_name, last_name, middle_name, group_id) VALUES ('000001', 'Дмитрий', 'Перминов', 'Сергеевич', 1);
INSERT INTO public.students (credit_card, first_name, last_name, middle_name, group_id) VALUES ('000001', 'Виталий', 'Постников', 'Сергеевич', 1);
INSERT INTO public.students (credit_card, first_name, last_name, middle_name, group_id) VALUES ('000001', 'Владимир', 'Ронжин', 'Сергеевич', 1);
INSERT INTO public.students (credit_card, first_name, last_name, middle_name, group_id) VALUES ('000001', 'Арсений', 'Халявин', 'Константинович', 1);
INSERT INTO public.students (credit_card, first_name, last_name, middle_name, group_id) VALUES ('000001', 'Павел', 'Целищев', 'Александрович', 1);
INSERT INTO public.students (credit_card, first_name, last_name, middle_name, group_id) VALUES ('000001', 'Марина', 'Шишкина', 'Андреевна', 1);
INSERT INTO public.students (credit_card, first_name, last_name, middle_name, group_id) VALUES ('000001', 'Аркадий', 'Шубин', 'Анатольевич', 1);
INSERT INTO public.students (credit_card, first_name, last_name, middle_name, group_id) VALUES ('000001', 'Дмитрий', 'Бушманов', 'Сергеевич', 2);
INSERT INTO public.students (credit_card, first_name, last_name, middle_name, group_id) VALUES ('000001', 'Евгений', 'Воробьёв', 'Сергеевич', 2);
INSERT INTO public.students (credit_card, first_name, last_name, middle_name, group_id) VALUES ('000001', 'Никита', 'Глухих', 'Сергеевич', 2);
INSERT INTO public.students (credit_card, first_name, last_name, middle_name, group_id) VALUES ('000001', 'Артемий', 'Истомин', 'Всеволодович', 2);
INSERT INTO public.students (credit_card, first_name, last_name, middle_name, group_id) VALUES ('000001', 'Антон', 'Канев', 'Васильевич', 2);
INSERT INTO public.students (credit_card, first_name, last_name, middle_name, group_id) VALUES ('000001', 'Олег', 'Комаров', 'Александрович', 2);
INSERT INTO public.students (credit_card, first_name, last_name, middle_name, group_id) VALUES ('000001', 'Иван', 'Лубнин', 'Александрович', 2);
INSERT INTO public.students (credit_card, first_name, last_name, middle_name, group_id) VALUES ('000001', 'Данила', 'Можегов', 'Сергеевич', 2);
INSERT INTO public.students (credit_card, first_name, last_name, middle_name, group_id) VALUES ('000001', 'Виктория', 'Рякина', 'Александровна', 2);
INSERT INTO public.students (credit_card, first_name, last_name, middle_name, group_id) VALUES ('000001', 'Анастасия', 'Хабаровская', 'Алексеевна', 2);
INSERT INTO public.students (credit_card, first_name, last_name, middle_name, group_id) VALUES ('000001', 'Дмитрий', 'Целищев', 'Алексеевич', 2);
INSERT INTO public.students (credit_card, first_name, last_name, middle_name, group_id) VALUES ('000001', 'Михаил', 'Шабалин', 'Суренович', 2);
INSERT INTO public.students (credit_card, first_name, last_name, middle_name, group_id) VALUES ('000001', 'Антон', 'Шутов', 'Алексеевич', 2);
INSERT INTO public.students (credit_card, first_name, last_name, middle_name, group_id) VALUES ('000001', 'Николай', 'Шутов', 'Константинович', 2);